import styles from "./page.module.scss";

export default function Home() {
  return (
    <main className={styles.main}>
      <h1>Home Page </h1>
    <p className={styles.p}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare neque quam, sit amet fringilla purus scelerisque quis. Mauris iaculis hendrerit viverra. Maecenas consectetur sagittis sapien, sit amet eleifend neque convallis vel. Nunc lobortis aliquet tellus eget convallis. Etiam vel tellus non ex eleifend efficitur. Pellentesque at hendrerit velit. Mauris vestibulum at risus vel fermentum. Phasellus eget dolor fringilla, gravida quam et, hendrerit dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut nulla nec lorem viverra auctor. Mauris aliquet libero ut est pretium iaculis. Vivamus volutpat facilisis sapien sit amet mollis. Cras nunc lectus, sodales vitae lacus at, consectetur convallis nibh. Nulla luctus fermentum arcu, eget feugiat magna bibendum nec. Sed nec ipsum sodales, tristique orci ac, consectetur tellus. Duis id ex vitae nisi lacinia commodo ut quis eros. </p>
    <p className={styles.p}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare neque quam, sit amet fringilla purus scelerisque quis. Mauris iaculis hendrerit viverra. Maecenas consectetur sagittis sapien, sit amet eleifend neque convallis vel. Nunc lobortis aliquet tellus eget convallis. Etiam vel tellus non ex eleifend efficitur. Pellentesque at hendrerit velit. Mauris vestibulum at risus vel fermentum. Phasellus eget dolor fringilla, gravida quam et, hendrerit dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut nulla nec lorem viverra auctor. Mauris aliquet libero ut est pretium iaculis. Vivamus volutpat facilisis sapien sit amet mollis. Cras nunc lectus, sodales vitae lacus at, consectetur convallis nibh. Nulla luctus fermentum arcu, eget feugiat magna bibendum nec. Sed nec ipsum sodales, tristique orci ac, consectetur tellus. Duis id ex vitae nisi lacinia commodo ut quis eros. </p>
    <p className={styles.p}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare neque quam, sit amet fringilla purus scelerisque quis. Mauris iaculis hendrerit viverra. Maecenas consectetur sagittis sapien, sit amet eleifend neque convallis vel. Nunc lobortis aliquet tellus eget convallis. Etiam vel tellus non ex eleifend efficitur. Pellentesque at hendrerit velit. Mauris vestibulum at risus vel fermentum. Phasellus eget dolor fringilla, gravida quam et, hendrerit dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut nulla nec lorem viverra auctor. Mauris aliquet libero ut est pretium iaculis. Vivamus volutpat facilisis sapien sit amet mollis. Cras nunc lectus, sodales vitae lacus at, consectetur convallis nibh. Nulla luctus fermentum arcu, eget feugiat magna bibendum nec. Sed nec ipsum sodales, tristique orci ac, consectetur tellus. Duis id ex vitae nisi lacinia commodo ut quis eros. </p>
    <p className={styles.p}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare neque quam, sit amet fringilla purus scelerisque quis. Mauris iaculis hendrerit viverra. Maecenas consectetur sagittis sapien, sit amet eleifend neque convallis vel. Nunc lobortis aliquet tellus eget convallis. Etiam vel tellus non ex eleifend efficitur. Pellentesque at hendrerit velit. Mauris vestibulum at risus vel fermentum. Phasellus eget dolor fringilla, gravida quam et, hendrerit dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut nulla nec lorem viverra auctor. Mauris aliquet libero ut est pretium iaculis. Vivamus volutpat facilisis sapien sit amet mollis. Cras nunc lectus, sodales vitae lacus at, consectetur convallis nibh. Nulla luctus fermentum arcu, eget feugiat magna bibendum nec. Sed nec ipsum sodales, tristique orci ac, consectetur tellus. Duis id ex vitae nisi lacinia commodo ut quis eros. </p>
    <p className={styles.p}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare neque quam, sit amet fringilla purus scelerisque quis. Mauris iaculis hendrerit viverra. Maecenas consectetur sagittis sapien, sit amet eleifend neque convallis vel. Nunc lobortis aliquet tellus eget convallis. Etiam vel tellus non ex eleifend efficitur. Pellentesque at hendrerit velit. Mauris vestibulum at risus vel fermentum. Phasellus eget dolor fringilla, gravida quam et, hendrerit dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut nulla nec lorem viverra auctor. Mauris aliquet libero ut est pretium iaculis. Vivamus volutpat facilisis sapien sit amet mollis. Cras nunc lectus, sodales vitae lacus at, consectetur convallis nibh. Nulla luctus fermentum arcu, eget feugiat magna bibendum nec. Sed nec ipsum sodales, tristique orci ac, consectetur tellus. Duis id ex vitae nisi lacinia commodo ut quis eros. </p>
    <p className={styles.p}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare neque quam, sit amet fringilla purus scelerisque quis. Mauris iaculis hendrerit viverra. Maecenas consectetur sagittis sapien, sit amet eleifend neque convallis vel. Nunc lobortis aliquet tellus eget convallis. Etiam vel tellus non ex eleifend efficitur. Pellentesque at hendrerit velit. Mauris vestibulum at risus vel fermentum. Phasellus eget dolor fringilla, gravida quam et, hendrerit dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut nulla nec lorem viverra auctor. Mauris aliquet libero ut est pretium iaculis. Vivamus volutpat facilisis sapien sit amet mollis. Cras nunc lectus, sodales vitae lacus at, consectetur convallis nibh. Nulla luctus fermentum arcu, eget feugiat magna bibendum nec. Sed nec ipsum sodales, tristique orci ac, consectetur tellus. Duis id ex vitae nisi lacinia commodo ut quis eros. </p>
    <p className={styles.p}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare neque quam, sit amet fringilla purus scelerisque quis. Mauris iaculis hendrerit viverra. Maecenas consectetur sagittis sapien, sit amet eleifend neque convallis vel. Nunc lobortis aliquet tellus eget convallis. Etiam vel tellus non ex eleifend efficitur. Pellentesque at hendrerit velit. Mauris vestibulum at risus vel fermentum. Phasellus eget dolor fringilla, gravida quam et, hendrerit dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut nulla nec lorem viverra auctor. Mauris aliquet libero ut est pretium iaculis. Vivamus volutpat facilisis sapien sit amet mollis. Cras nunc lectus, sodales vitae lacus at, consectetur convallis nibh. Nulla luctus fermentum arcu, eget feugiat magna bibendum nec. Sed nec ipsum sodales, tristique orci ac, consectetur tellus. Duis id ex vitae nisi lacinia commodo ut quis eros. </p>
    <p className={styles.p}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare neque quam, sit amet fringilla purus scelerisque quis. Mauris iaculis hendrerit viverra. Maecenas consectetur sagittis sapien, sit amet eleifend neque convallis vel. Nunc lobortis aliquet tellus eget convallis. Etiam vel tellus non ex eleifend efficitur. Pellentesque at hendrerit velit. Mauris vestibulum at risus vel fermentum. Phasellus eget dolor fringilla, gravida quam et, hendrerit dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut nulla nec lorem viverra auctor. Mauris aliquet libero ut est pretium iaculis. Vivamus volutpat facilisis sapien sit amet mollis. Cras nunc lectus, sodales vitae lacus at, consectetur convallis nibh. Nulla luctus fermentum arcu, eget feugiat magna bibendum nec. Sed nec ipsum sodales, tristique orci ac, consectetur tellus. Duis id ex vitae nisi lacinia commodo ut quis eros. </p>
    <p className={styles.p}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare neque quam, sit amet fringilla purus scelerisque quis. Mauris iaculis hendrerit viverra. Maecenas consectetur sagittis sapien, sit amet eleifend neque convallis vel. Nunc lobortis aliquet tellus eget convallis. Etiam vel tellus non ex eleifend efficitur. Pellentesque at hendrerit velit. Mauris vestibulum at risus vel fermentum. Phasellus eget dolor fringilla, gravida quam et, hendrerit dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut nulla nec lorem viverra auctor. Mauris aliquet libero ut est pretium iaculis. Vivamus volutpat facilisis sapien sit amet mollis. Cras nunc lectus, sodales vitae lacus at, consectetur convallis nibh. Nulla luctus fermentum arcu, eget feugiat magna bibendum nec. Sed nec ipsum sodales, tristique orci ac, consectetur tellus. Duis id ex vitae nisi lacinia commodo ut quis eros. </p>
    <p className={styles.p}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare neque quam, sit amet fringilla purus scelerisque quis. Mauris iaculis hendrerit viverra. Maecenas consectetur sagittis sapien, sit amet eleifend neque convallis vel. Nunc lobortis aliquet tellus eget convallis. Etiam vel tellus non ex eleifend efficitur. Pellentesque at hendrerit velit. Mauris vestibulum at risus vel fermentum. Phasellus eget dolor fringilla, gravida quam et, hendrerit dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut nulla nec lorem viverra auctor. Mauris aliquet libero ut est pretium iaculis. Vivamus volutpat facilisis sapien sit amet mollis. Cras nunc lectus, sodales vitae lacus at, consectetur convallis nibh. Nulla luctus fermentum arcu, eget feugiat magna bibendum nec. Sed nec ipsum sodales, tristique orci ac, consectetur tellus. Duis id ex vitae nisi lacinia commodo ut quis eros. </p>
    <p className={styles.p}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ornare neque quam, sit amet fringilla purus scelerisque quis. Mauris iaculis hendrerit viverra. Maecenas consectetur sagittis sapien, sit amet eleifend neque convallis vel. Nunc lobortis aliquet tellus eget convallis. Etiam vel tellus non ex eleifend efficitur. Pellentesque at hendrerit velit. Mauris vestibulum at risus vel fermentum. Phasellus eget dolor fringilla, gravida quam et, hendrerit dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut nulla nec lorem viverra auctor. Mauris aliquet libero ut est pretium iaculis. Vivamus volutpat facilisis sapien sit amet mollis. Cras nunc lectus, sodales vitae lacus at, consectetur convallis nibh. Nulla luctus fermentum arcu, eget feugiat magna bibendum nec. Sed nec ipsum sodales, tristique orci ac, consectetur tellus. Duis id ex vitae nisi lacinia commodo ut quis eros. </p>
    </main>
  );
}
